---
format: gfm
number-sections: true
title: NetGen
---

The aim of this repo is to experiment with ways of generating route networks for transport planning that:

- Maximise readability, reproducibility and ease of using and extending the code
- Minimise the number of lines of code
- Minimise the number of dependencies
- Maximise flexibility, for example enabling 'low resolution' or 'high resolution' networks to be generated by changing a single parameter
- Maximise efficiency in terms of programmer and computer time

Building on previous work on the PCT, CRUSE and NPT web applications, the approach is implemented in R in the first instance.
The idea is for the approach to be generalisable enough to be easily ported to other languages in the future.

# Inputs

There are two main types of inputs: required and optional.

## Required inputs

- Configuration parameters which can be stored in a plaintext file
- OpenStreetMap data

## Optional inputs

- Origin-destination data, e.g. representing travel to work, school, leisure centres or for all purposes
- Administrative boundaries representing origins and destinations, often with additional attributes such as population
- Data on known trip attractors, e.g. schools, hospitals, leisure centres, shops, etc.
- Data on population density, e.g. from Facebook's High Resolution Population Density Maps

# Outputs